Update appium-tests.yml

diff --git a/.github/workflows/appium-tests.yml b/.github/workflows/appium-tests.yml
--- a/.github/workflows/appium-tests.yml
+++ b/.github/workflows/appium-tests.yml
@@ -32,15 +32,25 @@ jobs:
     - name: Check Android SDK directory
       run: ls -l $ANDROID_HOME
 
-    - name: create AVD 
-      run: $ANDROID_HOME/tools/bin/avdmanager create avd -d "Nexus 10" -n test1 -k "system-images;android-30;google_apis_playstore;x86_64"
+    - name: Create AVD
+      run: |
+        $ANDROID_HOME/tools/bin/avdmanager create avd -d "Nexus 10" -n test1 -k "system-images;android-30;google_apis_playstore;x86_64"
+        if [ $? -ne 0 ]; then
+          echo "Failed to create AVD."
+          exit 1
+        fi
+        
     - name: List AVD Devices
       run: $ANDROID_HOME/emulator/emulator -list-avds
+
     - name: Run AVD Devices
-      run: $ANDROID_HOME/emulator/emulator -avd test1
+      run: |
+        $ANDROID_HOME/emulator/emulator -avd test1 &
+        sleep 60  # Adjust sleep time as needed, wait for emulator to fully start
+
     - name: List ADB Devices
       run: adb devices
-
+        
     - name: Install Dependencies
       run: mvn install --quiet
 
